FROM node:22.14.0-alpine3.21

WORKDIR /app

COPY package.json ./
RUN npm install

# Don't build; ng serve will run directly with file watching
EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
